# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/coraz7.xdc

# Block Designs: bd/axispi/axispi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axispi || ORIG_REF_NAME==axispi} -quiet] -quiet

# IP: bd/axispi/ip/axispi_spi_axi_lite_0_0/axispi_spi_axi_lite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axispi_spi_axi_lite_0_0 || ORIG_REF_NAME==axispi_spi_axi_lite_0_0} -quiet] -quiet

# IP: bd/axispi/ip/axispi_processing_system7_0_0/axispi_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axispi_processing_system7_0_0 || ORIG_REF_NAME==axispi_processing_system7_0_0} -quiet] -quiet

# IP: bd/axispi/ip/axispi_ps7_0_axi_periph_0/axispi_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axispi_ps7_0_axi_periph_0 || ORIG_REF_NAME==axispi_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axispi/ip/axispi_rst_ps7_0_50M_0/axispi_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axispi_rst_ps7_0_50M_0 || ORIG_REF_NAME==axispi_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/axispi/ip/axispi_auto_pc_0/axispi_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axispi_auto_pc_0 || ORIG_REF_NAME==axispi_auto_pc_0} -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/Cora-Z7-07s-SPI-AXI/Cora-Z7-07s-SPI-AXI.gen/sources_1/bd/axispi/axispi_ooc.xdc
